algoritmo "Meu primeiro algoritimo"

var

nome:caracter
idade:inteiro
altura:real
casado:logico

inicio

escreva("Digite seu nome:")
leia(nome)
escreva("Digite sua idade:")
leia(idade)
escreva("Digite sua altura:")
leia(altura)
escreva("Estado civil:")
leia(casado)
escreval("Seu nome e ", nome, "sua idade e", idade, "sua altura e", altura, "estado civil", casado)

fimalgoritmo