Algoritmo "semnome"
// 
//  
// Descrição   : Programa verifica a idade e verifica se pode tirar CNB
// Autor(a)    : Bruno Aquino
// Data atual  : 21/9/2020
Var
// Seção de Declarações das variáveis 
idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe sua idade :")
leia(idade)

se (idade >= 18) entao
escreva("Voce pode tirar sua CNH")
senao
escreva("Voce NAO pode tirar sua CNH")
fimse

Fimalgoritmo