Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/9/2020
Var
// Seção de Declarações das variáveis 
contador:inteiro
tabuada:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Informe um valor de 1 a 10:")
leia(tabuada)

para contador de 1 ate 10 faca
escreval(tabuada, "x", contador, "=", tabuada*contador)
fimpara

Fimalgoritmo